#!/bin/bash

if [ "$#" -ne 3 ]; then
  echo "Usage: ./search latitude=<LATITUDE> longitude=<LONGITUDE> radius=<RADIUS>"
  echo "Example: ./search latitude=48.8319929 longitude=2.3245488 radius=100"
  exit 1
fi

./venv/bin/python3 src/main.py $1 $2 $3
